       

name: python_flask_mysql 
services:
  app:
    container_name: web_app1
    build: ./app
    links: 
      - db-mysql
      - db-mssql
    ports: 
      - "800:8000"


  db-mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysql_db
    ports:
      - "336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw
  
  db-mssql:
    image: mcmoe/mssqldocker:v2017.CU30.0
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 2astazeY
      MSSQL_DB: dev
      MSSQL_USER: Kobeissi
      MSSQL_PASSWORD: 7ellowEl7akey
    ports:
    - "1433:1433"
    container_name: mssqldev